### ISSUE TITLE
Abbreviated format may need an update

### ISSUE THREAD

**Issue by fruehaufm** [CERTCC/SSVC#177]
I'm testing the demo site https://democert.org/ssvc/. I think the algorithm for deriving the abbreviated form seems to be outdated in `doc/md_src_files/060_decision-trees.md`. The abbreviation seems to be only one letter by now, not two letters as mentioned in the md file.

**Comment by sei-vsarvepalli** [comment]
Hello @fruehaufm 

Thank you for catching this as well. We may need to update the abbreviation document, as the timestamp format is also updated to be ISO8601 instead of Unix Epoch.  I think we can update the document to say the Keys can be derived in the recommended format or absorbed from the JSON as-is.  

Let me update once we have some time to discuss this internally to quality that my answers are actually correct.

Vijay
