### ISSUE TITLE
Add *inactive* option to Coordinator Triage tree

### ISSUE THREAD

**Issue by j---** [CERTCC/SSVC#203]
Add a fourth option (inactive) as a decision for the coordinator triage tree. 
These issues / vuls might still be tracked in a loose sense, but they will not be tracked closely and may be closed cases which could, hypothetically, be reopened but are not expected to be. 
This better aligns with how VINCE actually makes use of triage decisions.

**Comment by ahouseholder** [comment]
just mapping out effects of this change

- [ ] add text to [058_coordination.md](https://github.com/CERTCC/SSVC/blob/main/doc/md_src_files/058_coordination.md)
- [ ] update [coord-triage-options_v2.csv](https://github.com/CERTCC/SSVC/blob/main/data/csvs/coord-triage-options_v2.csv)
- [ ] update [ssvc_2_coord-triage.tex](https://github.com/CERTCC/SSVC/blob/main/doc/graphics/ssvc_2_coord-triage.tex)
- [ ] update [ssvc_2_coord-triage.pdf](https://github.com/CERTCC/SSVC/blob/main/doc/graphics/ssvc_2_coord-triage.pdf)
- [ ] update [Coordinator-Triage-v2.0.0.json](https://github.com/CERTCC/SSVC/blob/main/ssvc-calc/Coordinator-Triage-v2.0.0.json)

**Comment by ehatleback** [comment]
Rather than make an adjustment specifically for the tuple (VINCE, CERT/CC coordination decisions), a better adjustment would be to the generalized tuple ("General Coordination Platform" [Vultron?], "General Coordinator decisions).  

That is to say: the gain from making a singular adjustment now to the existing SSVC Coordination Tree is minimal in exchange for the effort involved to include "Inactive" leaves on the tree.  Nonetheless, the generalization of the Coordination Tree, perhaps for use by coordinator stakeholders who implement Vultron (for example) would definitely be worthwhile as an inclusion in the next major overhaul / update to SSVC.

**Comment by ahouseholder** [comment]
After some additional consideration, we're going to close this as a `wontfix` as it muddies the abstraction between

- The SSVC Coordinator Triage tree as a generic model of a coordinator's intake decision which should be fairly broadly applicable to coordinators in general
- The coordination process and states implemented in [VINCE](https://github.com/CERTCC/VINCE)
- CERT/CC's internal case handling process which _uses_ VINCE (and from which VINCE's requirements have to date largely derived)

Our preference at this time is not to tightly couple SSVC's Coordinator Triage decision model to CERT/CC's internal use of VINCE.
