### ISSUE TITLE
Technical impact assumes a vul has technical impact

### ISSUE THREAD

**Issue by j---** [CERTCC/SSVC#31]
We were assuming that for there to be a vulnerability, there has to be a technical impact. Make sure this is clear.
There is space to talk about how/when vul mgmt should document things that are not vuls, or some pointer to that discussion. The intended scope for SSVC is "so you've decided there is a vul, what are you going to do about it." But that isn't clear up front, so connect this aspect of the choice about technical impact to some discussion earlier in the document / intro.

**Comment by cgyarbrough** [comment]
I think that the premise might need to be re-examined. Vulnerabilities can exist but if they are not in an exploitable environment then there may be no technical impact. From a risk management standpoint, mitigations 'hide' vulnerabilities all the time, but they assume that the mitigation removes the risk of exploitation. I think we should talk about technical impact as being the operative phrase here, rather than the presence of a vulnerability (obviously without a vulnerability there would be no issue). I look at vulnerabilities as a risk manager might--how likely is this to hurt me? Many times management will decide not to address a vulnerability because the cost of fixes/mitigations exceed the perceived cost of being exploited.

**Comment by j---** [comment]
Thanks, these are good points. I think many of them are handled in other issues or parts of the SSVC document, but this is a good opportunity to link them together.  
> not in an exploitable environment
I think this is covered by *Exposure* https://github.com/CERTCC/SSVC/blob/main/doc/version_1/042_treesForVulMgmt_2.md
I think we clarified this already under #17, but there may be more to do to improve the description of *Exposure*.  

> there may be no technical impact
I think you've picked up on something that may need to be improved in the technical impact description, which is that the decision point evaluates the  technical impact on the vulnerable component if the vulnerability is exploited. "if the vulnerability is exploited" is currently implicit and could be made explicit. Can you file this under a new issue? 

> mitigations 'hide' vulnerabilities all the time
I think this is #78 and #79 

> how likely is this to hurt me? 
I think this falls under #66  and #49.

> not to address a vulnerability because the cost of fixes/mitigations
This is filed under #35 

This issue (#31) was intended to just clarify why there is no "none" option for *Technical Impact* (there is a none option for the C I A impact metrics in CVSS, so there is some potential for confusion if people are trying to directly compare those metrics with this decision point; that comparison is for #30).
