### ISSUE TITLE
What is the unit that is scored? 

### ISSUE THREAD

**Issue by j---** [CERTCC/SSVC#32]
The scope section is clear that "we assign the vulnerability to the nearest, relevant—yet more abstract—discrete component." However, we are generally scoring "units of work." How are these two related? Are we moving away from scoring individual issues and move to scoring the overarching system, be that a library, module, OS or other system? Either way, document the reasoning behind the answer.

**Comment by ahouseholder** [comment]
So what do we mean by "units of work"? 

From previous discussions I think this is related to the observation that vendors usually release patch bundles, not individual patches, and therefore appliers/remediators are prioritizing patch bundles.

This seems to set up a difference in scope between the vendor/developer/supplier (at the individual vul level) and the applier/remediator (at the patch bundle level). My suggestion would be that the applier/remediator uses

max([ssvc(vul) for vul in bundle])

as the priority. Does that make sense to others?

**Comment by j---** [comment]
I think the specific thing we want to address here is that if a work item is a patch bundle, then there are also potentially multiple discrete components to which the patches in that bundle apply. The interaction between those two possibilities is the core part of this issue. 

If a developer/supplier is updating the use of a library or something, the same might apply to them. Agreed that situation is less common.
 
There is overlap with #5 here in that "patch" was over-emphasized in v1, and I think we want to figure out whether there is any such thing as a combination of a non-patch mitigation and a patch on two separate vuls that need to be aggregated in some way. That is, is "patch bundle" actually the only relevant grouping of responses to vuls. 

I'd like to avoid a function to summarize multiple SSVC scores into one. The analyst should score the work item as a work item, not short cut by aggregating scores. The problem with aggregating scores is that there are various non-linear effects with systems-of-systems and there is likely not a one-size-fits-most solution for the best function.

**Comment by j---** [comment]
In 040_treesForVulMgmt.md , there are some headers that say "patches," as in deploy/supply patches, and this will need to be reevaluated and likely changed before this issue can be closed.

**Comment by laurie-tyz** [comment]
I would suggest "mitigation" or "remediation" instead of 'patches', 'fixes', etc.

**Comment by zmanion** [comment]
The vulnerability is in some component, I'm find saying "software component" if we need a consistent term.

For unit of work I'll suggest "response activity" under the concept that SSVC is prioritizing response, a special case of response is "track" (or do nothing, or do nothing for now, but this is still an active choice), and other responses are possible.

Then, a (very) typical response is remediation (totally fix vul), another is mitigation (partially fix, reduce impact/exposure, block attack vectors, etc). From this [comment](https://github.com/CERTCC/SSVC/issues/46#issuecomment-715553709) in #46.

**Comment by j---** [comment]
I agree with "response activity" where "mitigation" and "remediation" are types of "response activity".

**Comment by ahouseholder** [comment]
I think the "what do you call the remediation action?" question is entirely distinct from this issue, so the last few comments strike me as nonsequiturs to _this_ discussion. Also, I think #5 addressed that part anyway. Regardless, if any renaming of remediation action terminology remains I'd suggest it be spun into its own issue as this one is complex enough without vocabulary mismatches.

The remaining issue here goes back to "What is the unit of work?", and I'll attempt to summarize the discussion so far to hopefully make it clear what our options are.

Terminology-wise, within this issue I'm going to use "fix_bundle" to mean a fairly atomic deployment unit, something you'd queue up in a sysadmin's work queue to deploy. These may be larger than a single vul fix and contain other features unrelated to security. Service packs are fix bundles, but so is any discrete unit of deployment (anything that makes the "update" button light up on your "check for updates" for example).

My use of vul, product, and library carry the usual meanings which I think are not ambiguous in this context.

1. Vendors usually receive and resolve (vul, product) tuples into (fix_bundle, product) tuples
2. Vendors sometimes receive (vul, library) tuples and must first generate (library, product) tuples in order to transitively resolve both to (vul, product) tuples, which ultimately resolve into (fix_bundle, product) tuples
3. Vendors sometimes receive (fix_bundle_in, library) tuples and need to map these as above to get to their own (fix_bundle_out, product) tuples
4. System owners receive (fix_bundle, product) and (vul, product) tuples and must generate (product, instance) tuples in order to transitively resolve to (fix_bundle, instance) tuples. The actions a system owner ultimately take are I believe keyed on (fix_bundle, instance) tuples.

For fix deployers / system owners, because SSVC takes the approach that the system's mission is relevant to the deployment priority, (fix_bundle, instance) seems to be the unit of work for that tree.

My opinion is that the (vul, product) tuple is the unit of work to which SSVC applies at the vendor level. This implies the need for vendors to be able to resolve whatever they receive to that level of granularity in order to make best use of SSVC. (SBOM seems well-placed to address that resolution process for scenarios 2 and 3 above.)

What do others think about this framing?

**Comment by j---** [comment]
I think that is accurate and clear.
