### ISSUE TITLE
Tool to distribute outcome set across a decision point group

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#336]
As a way to facilitate an SSVC bootstrapping exercise, we should create a tool that takes as input:

- a decision point group
- an outcome set

It should:

- map the decision point set into a partial order over its value combinations
- distribute the outcome set across those combinations
- perhaps with a few options
  - balanced: try to assign approximately the same number of leaf nodes to each outcome value
  - weighted: if the input includes weights on the outcome set, try to assign leaf nodes with approximately that frequency. 
  
If you think about it this way, you only have to implement the weighted version, then the balanced one is just a special default case where weight $w_i=1/N$ for an outcome set of size $|N|$

The approach I have in mind is to construct a digraph of the input space, do a topological sort, and then assign leaf nodes according to the weights.

This won't produce perfect policies, but it should get most users in the ballpark of something they could then tune for their own needs.

**Comment by j---** [comment]
I know that when I was drafting example trees, I roughly had a sort of pattern in mind. 
You see defer / scheduled in 
https://github.com/CERTCC/SSVC/blob/338cc456c9185339e98eaeaf8ceb34665867fb8a/data/csvs/supplier-options.csv#L2-L3
and then when State of Exploitation has stepped up, the same decision values lead to scheduled / out-of-cycle
https://github.com/CERTCC/SSVC/blob/338cc456c9185339e98eaeaf8ceb34665867fb8a/data/csvs/supplier-options.csv#L14-L15
And then out-of-cycle/immediate
https://github.com/CERTCC/SSVC/blob/338cc456c9185339e98eaeaf8ceb34665867fb8a/data/csvs/supplier-options.csv#L26-L27

In order to accomplish this outcome set draft, do we need to assign a relative importance to decision points within the group? Or some other way to encode some pattern like this? Or maybe we don't actually think what I did was a way we should automate drafting tree examples?

**Comment by j---** [comment]
OK, I think influencing the partial order like that makes sense. We'll have to see how we want it to handle things when we run into the pigeon hole principle. Somehow my intuition is that too much structure will make that harder, but I don't actually know.
