### ISSUE TITLE
Map CVSSv4 equivalence sets to CVSSv4 decision points

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#348]
CVSS v4 adds the concept of "equivalence sets", which are rules for converting CVSS v4 vector elements to categories in 6 different dimensions. We can easily model these as: DecisionPointGroup(CVSSv4 dp1, ..., etc.). We should do that and provide it to assist folks who are trying to map a CVSS-based process onto an SSVC-oriented decision model.

**Comment by j---** [comment]
The CVSS v4 spec says: 

> EQ1 → AV/PR/UI with 3 levels specified in Table 25
> EQ2 → AC/AT with 2 levels specified in Table 26
> EQ3 → VC/VI/VA with 3 levels specified in Table 27
> EQ4 → SC/SI/SA with 3 levels specified in Table 28
> EQ5 → E with 3 levels specified in Table 29
> EQ6 → VC/VI/VA+CR/CI/CA with 2 levels specified in Table 30
> 
> Since EQ3 and EQ6 are not independent they must be considered together
> 
> EQ3+EQ6 → determines 5 levels specified in Table 31

Note that since EQ3 and EQ6 are not independent, there are actually 5 equivalence classes, not 6. The reason for this is a historical quirk in the way the development happened in the SIG. The two classes were independent in a non-public draft.  I think we can gloss over that historical accident and just have the 5 equivalence classes when we map it. 

Anyway, those tables and such are here https://www.first.org/cvss/v4.0/specification-document#CVSS-v4-0-Scoring-using-MacroVectors-and-Interpolation 

My intent with the equivalence classes was that they provide meaningful grouping of the CVSS metric groups. EQ3 is about vulnerable system impact, EQ4 is about subsequent system impact, etc. The challenge is that the "Exploitability" metric group is represented by EQ1 and EQ2, so it's not perfect. But would like feedback on if we should map them with their metric group names, which I think is easier to understand, or use the numbers directly from the specification?

**Comment by ahouseholder** [comment]
I think in general names are preferable in SSVC. I think you might be the only one to have a direct lookup in you head to dereference the numbered groups. 😀
