### ISSUE TITLE
Incorporate "fix" vs "mitigate" into SSVC decision process

### ISSUE THREAD

**Issue by laurie-tyz** [CERTCC/SSVC#76]
The "fix" actions, once completed, should close the vulnerability management case and not invite recursion. This makes applying a patch qualitatively different from completing a remediation. It's unclear the best way to explain or notate this.

 - [ ] Decide on most accessible method of incorporating "fix" vs "mitigate" into the SSVC decision process.

(Related to issue #46)

**Comment by cgyarbrough** [comment]
Mitigation, from a tactical perspective, is an attempt to block or minimize risk to a vulnerable system without actually eliminating the vulnerability. Remediation, from that same perspective, is an attempt to eliminate a vulnerability in a specific system. Specific vulnerabilities in specific systems can be remediated, but that does not mean that the vulnerability can be 'disposed of' or eliminated from future consideration within an IT environment. Since software and systems are dynamic, a single vulnerability can be re-introduced after initial remediation through updates, software rollbacks, or other systemic actions that change the operating conditions within an environment. It is therefore important to continually monitor remediated systems for re-introduced vulnerabilities even after initial remediation.
