### ISSUE TITLE
Link mitigation to the SSVC decision points.

### ISSUE THREAD

**Issue by laurie-tyz** [CERTCC/SSVC#79]
- [x] For the defined mitigation actions, link them to the SSVC decision point that they can influence. 

(Associated with issue #46 )

**Comment by j---** [comment]
This is related to #78. I'd say #79 is a prerequisite for #78. While I think #78 is not achievable in SSVCv2.0, this one does seem achievable. 

#79 has a dependency on moving the defined remediation actions to their own subsection within "Enumerating decisions". Although it puts things a bit out of order in the document, my thought at the moment is to address #79 in that new subsection. It's a bit out of order because "enumerating decisions" comes before the decision point definitions. But I think that is OK, and might be helpful, in that the reader will get a preview of the names of the decision points and what actions they are related to before we give the whole detailed description. This might be a helpful bit of signposting.

**Comment by zmanion** [comment]
Link mitigation (not remediation) to decision points. E.g., a firewall rule changes/reduces System Exposure, then SSVC is assessed again, and a lower priority results.

**Comment by laurie-tyz** [comment]
Wording I'm thinking of adding.


Deploying a mitigation reduces the system exposure. In the suggested tree the system exposure can be reduced from ‘open’ to ‘controlled’ or from ‘controlled’ to ‘small’.  Depending how your decision tree is constructed there may be a cascading effect on the other decisions. In the end, this reduction in System Exposure may or may not result in a change to the priority for further action.

from Jono:
Financial well-being impact might be reduced with adequate fraud detection and insurance. Physical well-being impact might be reduced by physical barriers that restrict a robot's ability to interact with humans. Mission impact might be reduced by introducing back-up business flows that do not use the vulnerable component.

**Comment by laurie-tyz** [comment]
completed
