### ISSUE TITLE
automatability options

### ISSUE THREAD

**Issue by j---** [CERTCC/SSVC#89]
"slow" and "rapid" are not really appropriate for *automatability*.
Should just be "no" and "yes." "True" and "False" are also options, but I think yes and no are consistent with the rest of SSVC.

**Comment by ahouseholder** [comment]
In a subsequent conversation elsewhere, I think we concluded that this is really a question about _attacker efficiency_ and the proposed options are _rapid_ -> _automatable_ and _slow_ -> _attacker driven_

**Comment by j---** [comment]
Suggest title is "Automatable" and answers are just Yes/No. 

"frustrated by adequate" in kill chain step 4 feels a bit squishy. Try to make the failure condition more explicit.

**Comment by ahouseholder** [comment]
I am still struggling with my gut reaction that "no" doesn't really mean "impossible" here. As in: there are things that are easy to automate, see worms, although I hope we're not just equating automation with worm potential, because worms are only one kind of automated exploitation. 

And there are things that are harder to automate, but "hard" is a function of attacker motivation and resources. There may be a subset of things that are both hard to automate *and* resist automation (stochastic exploits where stochasticity is inherent to the vul and not a feature that can be overcome with development resources), but even these are not "Automatable? No" unless we use a definition of "no" that actually means "well probably not unless you're a national government". In essence, a "no" answer is asking you to make a broad statement about the current and near future state of technology development across all of humanity, and if we were good at that technological surprise would be rare.

The sharp falloff of the automation cost curve at N=1 is a concern too, because once *anyone* chooses to put in the engineering effort, the fruits of that labor are no longer as far out of reach for those without the engineering resources as they were before. (Analogously, pharma companies often say that the first pill costs a billion dollars, and the second one costs a penny.)

But perhaps more useful than me typing more opinionated arguments in to this text field is this: Can anyone cite examples of "Automatable? No" vuls?

It would help if we understood what other folks are thinking of when they assert that "Automatable" is the axis and that the answer is binary. I'd also be interested in knowing about vuls that individuals think are close to the line. This might be a calibration exercise and we're just drawing our yes/no lines at different likelihood levels.

**Comment by j---** [comment]
SSVC is temporal. So "no" would always mean "at this time". It can change
if someone presents code that in fact automates it. That's fine, other
decision points can change, too.

"No" specifically means one of the 4 kill chain steps isn't reliably
automatable. "Reliable" is doing some work here. Also recall the "worst
plausible" reasoning required in #Scope. Not worst possible.

I think I can turn this into a question where the answer is no, and make
that question explicit. That should make it more clear.

**Comment by j---** [comment]
I found it easier to make my suggestions as a PR (#97). Thoughts?

**Comment by ahouseholder** [comment]
Closing per #97
