### ISSUE TITLE
"Virulence" is not an obviously-meaningful term 

### ISSUE THREAD

**Issue by j---** [CERTCC/SSVC#9]
Consider renaming *Virulence* to something more evocative / descriptive, like "wormable." If *Virulence* remains the title, consider listing synonyms in the heading or foregrounding the common-sense intuition of what it means.

**Comment by ahouseholder** [comment]
Since we're borrowing terms from epidemiology, there are a few related terms that might help us figure this out:

- _virulence_ ["a pathogen's or microbe's ability to infect or damage a host"](https://en.wikipedia.org/wiki/Virulence)
- _infectivity_ ["the ability of a pathogen to establish an infection"](https://en.wikipedia.org/wiki/Infectivity) 
- _transmissibility_  is more about the spread of a pathogen between individuals https://en.wikipedia.org/wiki/Transmission_(medicine)

I think our intended meaning was less about virulence and more about infectivity or maybe transmissibility.

**Comment by ahouseholder** [comment]
_automatability_ might be close.

The closely related (to each other) concepts of 
- _combustibility_ propensity to burst into flame if exposed to the right conditions, i.e., heat
- _flammability_ propensity to ignite easily at ambient temperatures
are analogs to the thing I think we're trying to represent here too.

Also relevant: from [CVSS v3.1 ](https://www.first.org/cvss/specification-document)
- _Attack Vector (AV)_ (Network/Adjacent/Local/Physical)
- _Attack Complexity (AC)_ (Low/High)
- _Privileges Required (PR)_ (None / Low / High)
- _User Interaction (UI)_ (None / Required)

Seems like in support of #33 and #30 we ought to map the CVSS stuff into _slow/rapid_ or whatever the end result is.
